site_name: Kittitas Kasetsin (Oak)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: teal
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: deep purple

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kittitasoak
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kittitas/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption 

plugins:
  - glightbox
  - search

nav:
  - Welcome to my Documentation: index.md
  - Marketing: 
      - Tools: assets\Marketing\Marketing_tools.md
      - Knowledge: assets\Marketing\Marketing_knowledge.md
  - Cybersecurity:
      - Tools: assets\Cybersecurity\Cybersecurity_tools.md
      - Knowledge: assets\Cybersecurity\Cybersecurity_knowledge.md
  - Project Management:
      - Tools: assets\Project Management\Project_management_tools.md
      - Knowledge: assets\Project Management\Project_Management_knowledge.md
  - Others:
      - Tools: assets\Others\Others_tools.md
      - Knowledge: assets\Others\Others_knowledge.md

copyright: |
  &copy; 2023 <a href="https://github.com/kittitasoak"  target="_blank" rel="noopener">Kittitas Kasetsin</a>