site_name: Kittitas Kasetsin (Oak)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: teal
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: deep purple

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kittitasoak
    - icon: fontawesome/brands/twitter
      link: .
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kittitas/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Welcome to my Documentation: index.md
  - Marketing: Marketing.md
  - Cybersecurity: Cybersecurity.md
  - Project Management: Project_management.md
  - Others: Others.md

copyright: |
  &copy; 2023 <a href="https://github.com/kittitasoak"  target="_blank" rel="noopener">Kittitas Kasetsin</a>